### ISSUE TITLE
JSON double quotes

### ISSUE THREAD

**Issue by berland** [perbrage/sectoralarm#1]
Thanks for the code! In order to get it to work together with my 'jq' parser on the Linux command line, I needed to jump some hoops as the library uses single quotes and not double qoutes. As far as I can read, double quotes are the JSON standard.

**Comment by perbrage** [comment]
Hi,

You are right! But I am unsure what I can do about it as the data is coming from sector alarms API and then transformed using a third-party library. I'll poke around when I have some time to see what I can come up with.

Thanks!

**Comment by perbrage** [comment]
Just published a new npm, version 1.3.0 that should resolved this issue. Thank you for reporting the issue!
