### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by plastfuglen** [perbrage/sectoralarm#14]
Sorry for my noob question, but is this library deployable as a component in Home Assistant?

**Comment by perbrage** [comment]
Hi,

I am at this point not aware if anyone used this package to produce a HomeAssistant component. If I am not misstaken, Home Assistant components are written using the Python language, which means that this project needs to be rewritten (or use similar ones) to Python as a first step. Then someone could make it into a home assistant component.

I do believe that someone is working on a Python version however, but I don't know how far they have come on it.

There is a HomeBridge and a NodeRED version built on-top of this library, that might be usable from Home Assistant.
