### ISSUE TITLE
Sectoralarm package does not document how to obtain required IDs

### ISSUE THREAD

**Issue by josteink** [perbrage/sectoralarm#16]
The most important ID to get things working is site/panel-ID.

I eventually found the value I needed by intercepting the XHR traffic on [minside.sectoralarm.no](https://minside.sectoralarm.no) (`POST https://minside.sectoralarm.no/Panel/GetOverview/` to be specific!), but this is not obvious and should be better documented.

Sensor IDs kinda look required, but will be auto-detected/provided through other API-calls if you have the site-ID or panel-ID. This may be worth documenting too.

**Comment by perbrage** [comment]
Hi,

If I remember correctly, earlier the panelID (siteID) was available in the URL from SectorAlarm, but this may have changed. 

I will have a look at documentation when I have time. Thank you for your input.

**Comment by perbrage** [comment]
The readme now includes how to find SiteId and other identifiers.
