### ISSUE TITLE
eslint issues

### ISSUE THREAD

**Issue by frli4797** [perbrage/sectoralarm#9]
Found a few minor things with eslint. Like unused imports and vars, double quotes, indents and similar stuff. 

PR or leave?

**Comment by perbrage** [comment]
A PR those things would be welcomed. Just make sure you have the latest code I pushed today that resolved the info, status and locks issues. I also upgraded a few third library packages for security purposes.

**Comment by frli4797** [comment]
I'll push the eslint config as well. You can chose to have it in .gitignore as you please.

**Comment by perbrage** [comment]
Can I close this issue now?

**Comment by perbrage** [comment]
Hi,

Seems I did not pull this one. Can you check with the latest code if there are any conflicts?

**Comment by perbrage** [comment]
I closed the pull request for these issues, cause there were conflicts after doing to much on my end. If you feel you want to try again, go ahead. But I am adding new features in the near future as well, so you might want to wait a bit. 

Sorry
